---
apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: shirts4mike
build:
  artifacts:
  - image: treehouse/shirts4mike
    sync:
      manual:
      - src: src/**/*
        dest: /var/www/html
        strip: src/
deploy:
  helm:
    releases:
    - name: shirts4mike
      chartPath: chart
      valuesFiles:
      - minikube.values.yaml
      artifactOverrides:
        image: treehouse/shirts4mike
      namespace: default
  kubeContext: minikube
portForward:
- resourceType: service
  resourceName: shirts4mike
  port: 80
  localPort: 8080
profiles:
- name: staging
  patches:
  - op: replace
    path: /deploy/helm/releases/0/valuesFiles/0
    value: staging.values.yaml
  deploy:
    kubeContext: staging
- name: production
  patches:
  - op: replace
    path: /deploy/helm/releases/0/valuesFiles/0
    value: production.values.yaml
  build:
    tagPolicy:
      gitCommit:
        variant: CommitSha
  deploy:
    kubeContext: production
