---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shirts4mike
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/common-name: {{ .Values.hostname }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/server-alias: {{ .Values.hostname }},www.{{ .Values.hostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.hostname }},www.{{ .Values.hostname }}
spec:
  tls:
  - secretName: shirts4mike-crt
    hosts:
    - {{ .Values.hostname }}
    - www.{{ .Values.hostname }}
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shirts4mike
            port:
              number: 80

