version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0
jobs:
  build:
    parameters:
      role:
        type: string
        default: "arn:aws:iam::629370713955:role/circleci"
      tags:
        type: string
        default: "latest"
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          repo: shirts4mike
          assume-web-identity: true
          role-arn: << parameters.role >>
          tag: << pipeline.git.revision >>,<< parameters.tags >>
  deploy:
    parameters:
      environment:
        type: string
      role:
        type: string
        default: "arn:aws:iam::629370713955:role/circleci"
      service-name:
        type: string
        default: demo_shirts
      family:
        type: string
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          role_arn: << parameters.role >>
      - aws-ecs/update-service:
          family: << parameters.family >>
          service-name: << parameters.service-name >>
          cluster: ecs-<< parameters.environment >>
          force-new-deployment: true
          verify-revision-is-deployed: true

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          context: treehouse private
          tags: latest
          filters:
            branches:
              only: master
      - deploy:
          context: treehouse private
          requires: [build]
          service-name: demo_shirts
          family: demo_shirts
          environment: production
