
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: shirts4mike
spec:
  secretName: shirts4mike-crt
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - shirts4mike.com
  - www.shirts4mike.com
  acme:
    config:
    - dns01:
        provider: prod-aws
      domains:
      - shirts4mike.com
      - www.shirts4mike.com

---

